### ISSUE TITLE
model of pytorch

### ISSUE THREAD

**Issue by YongdongTan** [IsaacChanghau/VSLNet#12]
Thank you for sharing, it is very helpful to me. How can I get the weight of the pytorch model

**Comment by 26hzhang** [comment]
@YongdongTan Sorry, I did not maintain any pre-trained PyTorch model. This work was written in TensorFlow at very beginning, the PyTorch version was added recently. I evaluated and found it is inferior to the TF version for some ``unknown'' reasons (I have mentioned it in the README.md). Since the TF version works, so I did not spend much time on exploring why this situation happens.
