### ISSUE TITLE
Cannot find pre-processed features for ActivityNet

### ISSUE THREAD

**Issue by Aileenlingyu** [IsaacChanghau/VSLNet#5]
Hi, thank you a lot for the excellent work! 

I am trying to download all preprocessed features while I didn't find the preprocessed features for ActivityNet-Caption following the box link you provided, in the folder, there are only files for TaCos and Charades-STA, could you please help me check it?

Thank you a lot!

**Comment by IsaacChanghau** [comment]
Hi, I did not upload the preprocessed features for the ActivityNet-Captions dataset due to the space limitations of my Box drive. However, I uploaded the entire pipeline of downloading ANetCap videos from YouTube and extract their features (as placed in ``prepare/'' folder), you can follow the instruction in ``prepare/README.md'' to generate the visual features for ANetCap using either C3D or I3D models.

**Comment by lixiang-coder** [comment]
What is the fps of activitynet when process the data? (it's need for extract_activitynet.py'). thank you
